// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceCalculatorPOC;

#nullable disable

namespace PriceCalculatorPOC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250328184750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriceCalculatorPOC.Models.CustomizationFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.HasIndex("ElementId");

                    b.ToTable("CustomizationFeatures");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.FixedUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("FixedUnits");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.InteriorElement", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("ElementId");

                    b.HasIndex("RoomId");

                    b.ToTable("InteriorElements");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.Selection", b =>
                {
                    b.Property<int>("SelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SelectionId"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SelectionId");

                    b.HasIndex("ElementId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.CustomizationFeature", b =>
                {
                    b.HasOne("PriceCalculatorPOC.Models.InteriorElement", "InteriorElement")
                        .WithMany("CustomizationFeatures")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteriorElement");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.InteriorElement", b =>
                {
                    b.HasOne("PriceCalculatorPOC.Models.Room", "Room")
                        .WithMany("InteriorElements")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.Selection", b =>
                {
                    b.HasOne("PriceCalculatorPOC.Models.InteriorElement", "InteriorElement")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteriorElement");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.InteriorElement", b =>
                {
                    b.Navigation("CustomizationFeatures");
                });

            modelBuilder.Entity("PriceCalculatorPOC.Models.Room", b =>
                {
                    b.Navigation("InteriorElements");
                });
#pragma warning restore 612, 618
        }
    }
}
